services:
  postgres:
    image: postgres:16-alpine
    container_name: finance-postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - finance-network
    healthcheck: # avisa ao docker quando o banco está realmente pronto
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: finance-redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - finance-network

  backend:
    build: ./finance-backend
    container_name: finance-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - DB_HOST=postgres # reescreve o 'localhost' do yaml para o nome do serviço do banco
      - REDIS_HOST=redis
    depends_on:
      postgres:
        condition: service_healthy # o backend só inicia quando o healthcheck do postgres passar
    networks:
      - finance-network

  frontend-web:
    build:
      context: ./finance-frontend
      args:
        - VITE_API_URL=http://localhost:8080
    container_name: finance-frontend-web
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - finance-network

volumes:
  pgdata:
  redisdata:

networks:
  finance-network:
    driver: bridge