spring:
  application:
    name: finance-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/finance_db
    username: finance_admin
    password: super_secret_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080